name: auto releaser

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  pull_request_target:
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  fulfill:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}